# Vulnerability Suppression for Grype Container Scans
# https://oss.anchore.com/docs/reference/grype/configuration/

ignore:
  - vulnerability: GHSA-8qq5-rm4j-mr97
  - vulnerability: CVE-2025-59465
  - vulnerability: CVE-2025-55131
  - vulnerability: GHSA-r6q2-hw4h-h46w
  - vulnerability: CVE-2025-55130
  - vulnerability: GHSA-5j98-mcp5-4vw2
  - vulnerability: CVE-2025-9230
  - vulnerability: CVE-2025-69420
  - vulnerability: GHSA-34x7-hfp2-rc4v
  - vulnerability: CVE-2025-69419
  - vulnerability: CVE-2025-15467
  - vulnerability: CVE-2025-69421
  - vulnerability: CVE-2025-59464
  - vulnerability: CVE-2026-21637
  - vulnerability: CVE-2025-59466
  - vulnerability: GHSA-7h2j-956f-4vf2
  - vulnerability: GHSA-3ppc-4f35-3m26
  - vulnerability: GHSA-83g3-92jg-28cx