codecov:
  require_ci_to_pass: yes

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 10% 
    patch: # Settings for PR patches
      default:
        target: auto
        threshold: 10% # Adjust as needed
