codecov:
  require_ci_to_pass: yes

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: no

ignore:
  - "src/lib/apiv1_grpc_pb.js"
  - "src/lib/apiv1_pb.js"
  
coverage:
  status:
    project:
      default:
        target: auto
        threshold: 50% 
    patch: # Settings for PR patches
      default:
        target: auto
        threshold: 50% # Adjust as needed
