### NPM PUBLISH ###

# NOTE:
# Used to publish the Pepr dist to the npm registry
# In this file, we keep the *.ts intentionally
# Any other changes to Dockerfile should be reflected in Publish

# crane digest cgr.dev/chainguard/node-lts:latest-dev
FROM cgr.dev/chainguard/node-lts@sha256:6d9e76deb58c7ac850e3aefa6f1b894f2825a19404cd9aa0ea445dc489715fdf AS build

WORKDIR /app

COPY --chown=node:node . .

RUN npm ci

RUN npm run build 


FROM scratch AS dist

COPY --from=build /app/dist ./dist/
