### NPM PUBLISH ###

# NOTE:
# Used to publish the Pepr dist to the npm registry
# In this file, we keep the *.ts intentionally
# Any other changes to Dockerfile should be reflected in Publish

# crane digest cgr.dev/chainguard/node-lts:latest-dev
FROM cgr.dev/chainguard/node-lts@sha256:e68c211c8abc454d7b11ce0ccefc707886187b2db156b5fadb2103bc29d46804 AS build

WORKDIR /app

COPY --chown=node:node . .

RUN npm ci

RUN npm run build 


FROM scratch AS dist

COPY --from=build /app/dist ./dist/
