// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2023-Present The Pepr Authors

// Audits .grype.yaml for stale CVE suppressions, removes them, writes a workflow summary, and conditionally
// opens a PR.
//
// A suppression is stale if grype no longer matches it against the scanned image
// (i.e., it appears in config.ignore but not in the scan's ignoredMatches).

import { execFileSync } from "child_process";
import { readFileSync, writeFileSync, appendFileSync, mkdtempSync, rmSync } from "fs";
import { tmpdir } from "os";
import { join, sep } from "path";
import { load } from "js-yaml";

import {
  collectIgnoredIds,
  findStaleSuppressions,
  removeStaleEntries,
  type GrypeConfig,
  type GrypeScanResult,
  type AuditResult,
} from "./audit-grype-suppressions.lib";

// ---------------------------------------------------------------------------
// Environment
// ---------------------------------------------------------------------------

const IMAGE = process.env.IMAGE ?? "pepr:dev";
const GRYPE_YAML = process.env.GRYPE_YAML ?? ".grype.yaml";
const GRYPE_CMD = process.env.GRYPE_CMD ?? "grype";
const GITHUB_STEP_SUMMARY = process.env.GITHUB_STEP_SUMMARY ?? "";
const RUN_URL = process.env.RUN_URL ?? "";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function exec(cmd: string, args: string[]): string {
  return execFileSync(cmd, args, { encoding: "utf-8", maxBuffer: 50 * 1024 * 1024 }).trim();
}

function scanImage(): GrypeScanResult {
  const json = exec(GRYPE_CMD, [IMAGE, "--config", GRYPE_YAML, "--output", "json"]);
  return JSON.parse(json) as GrypeScanResult;
}

// ---------------------------------------------------------------------------
// Core audit
// ---------------------------------------------------------------------------

function logAuditFindings(staleIds: string[], skippedEntries: AuditResult["skippedEntries"]): void {
  if (skippedEntries.length > 0) {
    console.log("==> Skipping multi-key entries (cannot auto-remove):");
    for (const entry of skippedEntries) {
      console.log(`   ${entry.vulnerability} (keys: ${entry.keys.join(", ")})`);
    }
  }
  if (staleIds.length > 0) {
    console.log("==> Stale suppressions identified:");
    for (const id of staleIds) {
      console.log(`   ${id}`);
    }
  }
}

function auditSuppressions(): AuditResult {
  console.log(`==> Scanning ${IMAGE} with current suppression list...`);
  const scan = scanImage();

  const matchCount = (scan.matches ?? []).length;
  console.log(`Non-suppressed matches: ${matchCount}`);

  const config = load(readFileSync(GRYPE_YAML, "utf-8")) as GrypeConfig;
  const ignoredIds = collectIgnoredIds(scan);
  const { staleIds, skippedEntries } = findStaleSuppressions(config.ignore, ignoredIds);

  logAuditFindings(staleIds, skippedEntries);

  if (staleIds.length === 0) {
    console.log("No stale suppressions found — nothing to do.");
    return { staleIds: [], matchCount, skippedEntries };
  }

  const yamlContent = readFileSync(GRYPE_YAML, "utf-8");
  const updatedYaml = removeStaleEntries(yamlContent, staleIds);
  writeFileSync(GRYPE_YAML, updatedYaml);

  return { staleIds, matchCount, skippedEntries };
}

// ---------------------------------------------------------------------------
// PR creation / update
// ---------------------------------------------------------------------------

function buildPRContent(staleIds: string[], matchCount: number): { title: string; body: string } {
  const staleCount = staleIds.length;
  const entries = staleCount === 1 ? "entry" : "entries";
  const bullets = staleIds.map(id => `- ${id}`).join("\n");

  const title = `chore: remove ${staleCount} stale CVE suppression(s) from .grype.yaml`;
  const body = [
    "## Summary",
    "",
    `The weekly grype suppression audit found **${staleCount}** ${entries} in \`.grype.yaml\` ` +
      `that no longer match any vulnerability in the \`${IMAGE}\` image and can be safely removed.`,
    "",
    "## Removed suppressions",
    "",
    bullets,
    "",
    "## How this was determined",
    "",
    `The script scanned \`${IMAGE}\` with the current \`.grype.yaml\`. Suppressions whose ` +
      "vulnerability IDs did not appear in the scan's `ignoredMatches` (i.e., grype no longer " +
      `matches them) were identified as stale and removed. Non-suppressed match count: **${matchCount}**.`,
    "",
    `_Generated by the [Grype Suppression Audit](${RUN_URL}) workflow._`,
  ].join("\n");

  return { title, body };
}

function pushBranch(branch: string, staleCount: number): void {
  const commitMsg = `chore: remove ${staleCount} stale CVE suppression(s) from .grype.yaml`;

  exec("git", ["config", "user.name", "github-actions[bot]"]);
  exec("git", ["config", "user.email", "github-actions[bot]@users.noreply.github.com"]);
  exec("git", ["checkout", "-B", branch]);
  exec("git", ["add", ".grype.yaml"]);
  exec("git", ["commit", "-m", commitMsg]);
  exec("git", ["push", "origin", branch, "--force-with-lease"]);
}

function openOrUpdatePR(branch: string, title: string, body: string): string {
  const prJson = exec("gh", [
    "pr",
    "list",
    "--head",
    branch,
    "--state",
    "open",
    "--json",
    "number,url",
  ]);
  const openPRs = JSON.parse(prJson) as { number: number; url: string }[];

  if (openPRs.length > 1) {
    throw new Error(
      `Expected at most 1 open PR for branch ${branch}, found ${openPRs.length}. ` +
        "Close duplicates before re-running.",
    );
  }

  const tmpDir = mkdtempSync(join(tmpdir(), `pepr-grype-${sep}`));
  const bodyFile = join(tmpDir, "pr-body.md");
  try {
    writeFileSync(bodyFile, body);

    if (openPRs.length === 1) {
      const prNumber = String(openPRs[0].number);
      console.log(`Updating existing PR #${prNumber}...`);
      exec("gh", ["pr", "edit", prNumber, "--title", title, "--body-file", bodyFile]);
      return openPRs[0].url;
    } else {
      console.log("Opening new PR...");
      return exec("gh", [
        "pr",
        "create",
        "--title",
        title,
        "--body-file",
        bodyFile,
        "--head",
        branch,
        "--base",
        "main",
      ]);
    }
  } finally {
    rmSync(tmpDir, { recursive: true, force: true });
  }
}

function createOrUpdatePR(staleIds: string[], matchCount: number): string {
  const branch = "grype/suppression-audit";
  const { title, body } = buildPRContent(staleIds, matchCount);
  pushBranch(branch, staleIds.length);
  return openOrUpdatePR(branch, title, body);
}

// ---------------------------------------------------------------------------
// Workflow summary
// ---------------------------------------------------------------------------

function writeSummary(
  auditOutcome: "success" | "failure",
  prOutcome: "success" | "failure" | "skipped",
  staleIds: string[],
  prUrl: string,
): void {
  if (!GITHUB_STEP_SUMMARY) return;

  const staleCount = staleIds.length;
  const lines: string[] = ["# Grype Suppression Audit", ""];

  if (auditOutcome !== "success") {
    lines.push(
      `> **Warning**: The audit step did not complete successfully (outcome: ${auditOutcome}).`,
      "> Results below may be incomplete. Check the workflow logs for details.",
      "",
    );
  }

  lines.push(
    "| | |",
    "|---|---|",
    `| **Image scanned** | \`${IMAGE}\` |`,
    `| **Stale suppressions found** | ${staleCount} |`,
    "",
  );

  if (staleCount === 0 && auditOutcome === "success") {
    lines.push(
      "## All suppressions are still active",
      "",
      "No changes to `.grype.yaml` are needed.",
    );
  } else if (staleCount > 0) {
    lines.push("### Stale suppressions");
    for (const id of staleIds) {
      lines.push(`- ${id}`);
    }
    lines.push("");

    if (prOutcome === "success") {
      lines.push(
        "## PR created or updated",
        "",
        `The above suppressions were removed from \`.grype.yaml\`. A [PR has been opened or updated](${prUrl}) for review.`,
      );
    } else if (prOutcome === "skipped") {
      lines.push(
        "## PR step was skipped",
        "",
        "The stale suppressions above were detected but the PR step did not run.",
      );
    } else {
      lines.push(
        "## PR creation failed",
        "",
        `> **Warning**: The PR step failed (outcome: ${prOutcome}). Check the workflow logs for details.`,
      );
    }
    lines.push("");
  }

  appendFileSync(GITHUB_STEP_SUMMARY, lines.join("\n") + "\n");
}

// ---------------------------------------------------------------------------
// Error logging
// ---------------------------------------------------------------------------

function logError(label: string, err: unknown): void {
  console.error(`${label}:`);
  if (err instanceof Error) {
    console.error(err.stack ?? err.message);
    const execErr = err as Error & { stdout?: Buffer | string; stderr?: Buffer | string };
    if (execErr.stdout) console.error("stdout:", String(execErr.stdout));
    if (execErr.stderr) console.error("stderr:", String(execErr.stderr));
  } else {
    console.error(err);
  }
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

function main(): void {
  let auditOutcome: "success" | "failure" = "success";
  let prOutcome: "success" | "failure" | "skipped" = "skipped";
  let prUrl = "";
  let result: AuditResult = { staleIds: [], matchCount: 0, skippedEntries: [] };

  try {
    result = auditSuppressions();
  } catch (err) {
    auditOutcome = "failure";
    logError("Audit step failed", err);
  }

  if (auditOutcome === "success" && result.staleIds.length > 0) {
    try {
      prUrl = createOrUpdatePR(result.staleIds, result.matchCount);
      prOutcome = "success";
    } catch (err) {
      prOutcome = "failure";
      logError("PR step failed", err);
    }
  }

  writeSummary(auditOutcome, prOutcome, result.staleIds, prUrl);

  if (auditOutcome === "failure" || prOutcome === "failure") {
    process.exit(1);
  }
}

main();
