#!/bin/bash
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2023-Present The Pepr Authors
#
# Creates or updates the grype suppression audit PR.
# If a PR for the branch already exists it is updated in place rather than
# closed and recreated, so any reviewer comments are preserved.
#
# Expected environment variables:
#   STALE_COUNT  - number of stale suppressions removed
#   STALE_LIST   - newline-separated list of removed IDs
#   MATCH_COUNT  - non-suppressed match count after removal (for verification note)
#   RUN_URL      - URL of the workflow run (for PR footer)

set -euo pipefail

BRANCH="grype/suppression-audit"
ENTRY_WORD=$([ "${STALE_COUNT}" -eq 1 ] && echo "y" || echo "ies")
BULLETS="- ${STALE_LIST//$'\n'/$'\n'- }"

git config user.name "github-actions[bot]"
git config user.email "github-actions[bot]@users.noreply.github.com"
git checkout -b "${BRANCH}"
git add .grype.yaml
git commit -m "chore: remove ${STALE_COUNT} stale CVE suppression(s) from .grype.yaml"
git push origin "${BRANCH}" --force

cat > /tmp/pr-body.md <<EOF
## Summary

The weekly grype suppression audit found **${STALE_COUNT}** entr${ENTRY_WORD} in \`.grype.yaml\` that no longer match any vulnerability in the \`pepr:dev\` image and can be safely removed.

## Removed suppressions

${BULLETS}

## Verification

After removing these entries the script re-ran grype against \`pepr:dev\` with the updated \`.grype.yaml\`. The count of non-suppressed vulnerabilities was identical before and after removal (**${MATCH_COUNT}**), confirming that none of the removed entries were actively covering a live vulnerability in the image.

If this check had failed, the script would have aborted and this PR would not have been opened or updated.

_Generated by the [Grype Suppression Audit](${RUN_URL}) workflow._
EOF

TITLE="chore: remove ${STALE_COUNT} stale CVE suppression(s) from .grype.yaml"

EXISTING_PR=$(gh pr list \
  --head "${BRANCH}" \
  --state open \
  --json number \
  -q '.[0].number // empty')

if [ -n "${EXISTING_PR}" ]; then
  echo "Updating existing PR #${EXISTING_PR}..."
  gh pr edit "${EXISTING_PR}" \
    --title "${TITLE}" \
    --body-file /tmp/pr-body.md
else
  echo "Opening new PR..."
  gh pr create \
    --title "${TITLE}" \
    --body-file /tmp/pr-body.md \
    --head "${BRANCH}" \
    --base main
fi
