// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.1
//   protoc               v4.23.3
// source: apiv1.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientReadableStream,
  type handleServerStreamingCall,
  makeGenericClientConstructor,
  type Metadata,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";

export const protobufPackage = "api";

export enum EventType {
  EVENT_TYPE_UNSPECIFIED = 0,
  ADDED = 1,
  MODIFIED = 2,
  DELETED = 3,
  BOOKMARK = 4,
  ERROR = 5,
  /** SNAPSHOT_END - marker if sendInitialList=true */
  SNAPSHOT_END = 6,
  UNRECOGNIZED = -1,
}

export function eventTypeFromJSON(object: any): EventType {
  switch (object) {
    case 0:
    case "EVENT_TYPE_UNSPECIFIED":
      return EventType.EVENT_TYPE_UNSPECIFIED;
    case 1:
    case "ADDED":
      return EventType.ADDED;
    case 2:
    case "MODIFIED":
      return EventType.MODIFIED;
    case 3:
    case "DELETED":
      return EventType.DELETED;
    case 4:
    case "BOOKMARK":
      return EventType.BOOKMARK;
    case 5:
    case "ERROR":
      return EventType.ERROR;
    case 6:
    case "SNAPSHOT_END":
      return EventType.SNAPSHOT_END;
    case -1:
    case "UNRECOGNIZED":
    default:
      return EventType.UNRECOGNIZED;
  }
}

export function eventTypeToJSON(object: EventType): string {
  switch (object) {
    case EventType.EVENT_TYPE_UNSPECIFIED:
      return "EVENT_TYPE_UNSPECIFIED";
    case EventType.ADDED:
      return "ADDED";
    case EventType.MODIFIED:
      return "MODIFIED";
    case EventType.DELETED:
      return "DELETED";
    case EventType.BOOKMARK:
      return "BOOKMARK";
    case EventType.ERROR:
      return "ERROR";
    case EventType.SNAPSHOT_END:
      return "SNAPSHOT_END";
    case EventType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface WatchRequest {
  group: string;
  version: string;
  resource: string;
  /** Optional: Namespace to watch, empty for all namespaces */
  namespace: string;
  /** Selectors -- NEW */
  fieldSelector: string;
  /** Optional: Label selector for filtering */
  labelSelector: string;
  /** Informer Configuration */
  resyncPeriodSeconds: number;
  /** Optional: Whether to send initial list */
  sendInitialList: boolean;
  /** Optional: Resource version to start from */
  startResourceVersion: string;
}

export interface WatchResponse {
  /** e.g., "ADD", "UPDATE", "DELETE" */
  eventType: EventType;
  /** Details of the event */
  details: Uint8Array;
  /** Resource version of the event */
  resourceVersion: string;
}

function createBaseWatchRequest(): WatchRequest {
  return {
    group: "",
    version: "",
    resource: "",
    namespace: "",
    fieldSelector: "",
    labelSelector: "",
    resyncPeriodSeconds: 0,
    sendInitialList: false,
    startResourceVersion: "",
  };
}

export const WatchRequest: MessageFns<WatchRequest> = {
  encode(message: WatchRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.group !== "") {
      writer.uint32(10).string(message.group);
    }
    if (message.version !== "") {
      writer.uint32(18).string(message.version);
    }
    if (message.resource !== "") {
      writer.uint32(26).string(message.resource);
    }
    if (message.namespace !== "") {
      writer.uint32(34).string(message.namespace);
    }
    if (message.fieldSelector !== "") {
      writer.uint32(42).string(message.fieldSelector);
    }
    if (message.labelSelector !== "") {
      writer.uint32(50).string(message.labelSelector);
    }
    if (message.resyncPeriodSeconds !== 0) {
      writer.uint32(56).int32(message.resyncPeriodSeconds);
    }
    if (message.sendInitialList !== false) {
      writer.uint32(64).bool(message.sendInitialList);
    }
    if (message.startResourceVersion !== "") {
      writer.uint32(74).string(message.startResourceVersion);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): WatchRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseWatchRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.group = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.version = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.resource = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.namespace = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.fieldSelector = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.labelSelector = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.resyncPeriodSeconds = reader.int32();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.sendInitialList = reader.bool();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.startResourceVersion = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): WatchRequest {
    return {
      group: isSet(object.group) ? globalThis.String(object.group) : "",
      version: isSet(object.version) ? globalThis.String(object.version) : "",
      resource: isSet(object.resource) ? globalThis.String(object.resource) : "",
      namespace: isSet(object.namespace) ? globalThis.String(object.namespace) : "",
      fieldSelector: isSet(object.fieldSelector) ? globalThis.String(object.fieldSelector) : "",
      labelSelector: isSet(object.labelSelector) ? globalThis.String(object.labelSelector) : "",
      resyncPeriodSeconds: isSet(object.resyncPeriodSeconds) ? globalThis.Number(object.resyncPeriodSeconds) : 0,
      sendInitialList: isSet(object.sendInitialList) ? globalThis.Boolean(object.sendInitialList) : false,
      startResourceVersion: isSet(object.startResourceVersion) ? globalThis.String(object.startResourceVersion) : "",
    };
  },

  toJSON(message: WatchRequest): unknown {
    const obj: any = {};
    if (message.group !== "") {
      obj.group = message.group;
    }
    if (message.version !== "") {
      obj.version = message.version;
    }
    if (message.resource !== "") {
      obj.resource = message.resource;
    }
    if (message.namespace !== "") {
      obj.namespace = message.namespace;
    }
    if (message.fieldSelector !== "") {
      obj.fieldSelector = message.fieldSelector;
    }
    if (message.labelSelector !== "") {
      obj.labelSelector = message.labelSelector;
    }
    if (message.resyncPeriodSeconds !== 0) {
      obj.resyncPeriodSeconds = Math.round(message.resyncPeriodSeconds);
    }
    if (message.sendInitialList !== false) {
      obj.sendInitialList = message.sendInitialList;
    }
    if (message.startResourceVersion !== "") {
      obj.startResourceVersion = message.startResourceVersion;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<WatchRequest>, I>>(base?: I): WatchRequest {
    return WatchRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<WatchRequest>, I>>(object: I): WatchRequest {
    const message = createBaseWatchRequest();
    message.group = object.group ?? "";
    message.version = object.version ?? "";
    message.resource = object.resource ?? "";
    message.namespace = object.namespace ?? "";
    message.fieldSelector = object.fieldSelector ?? "";
    message.labelSelector = object.labelSelector ?? "";
    message.resyncPeriodSeconds = object.resyncPeriodSeconds ?? 0;
    message.sendInitialList = object.sendInitialList ?? false;
    message.startResourceVersion = object.startResourceVersion ?? "";
    return message;
  },
};

function createBaseWatchResponse(): WatchResponse {
  return { eventType: 0, details: new Uint8Array(0), resourceVersion: "" };
}

export const WatchResponse: MessageFns<WatchResponse> = {
  encode(message: WatchResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.eventType !== 0) {
      writer.uint32(8).int32(message.eventType);
    }
    if (message.details.length !== 0) {
      writer.uint32(18).bytes(message.details);
    }
    if (message.resourceVersion !== "") {
      writer.uint32(26).string(message.resourceVersion);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): WatchResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseWatchResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.eventType = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.details = reader.bytes();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.resourceVersion = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): WatchResponse {
    return {
      eventType: isSet(object.eventType) ? eventTypeFromJSON(object.eventType) : 0,
      details: isSet(object.details) ? bytesFromBase64(object.details) : new Uint8Array(0),
      resourceVersion: isSet(object.resourceVersion) ? globalThis.String(object.resourceVersion) : "",
    };
  },

  toJSON(message: WatchResponse): unknown {
    const obj: any = {};
    if (message.eventType !== 0) {
      obj.eventType = eventTypeToJSON(message.eventType);
    }
    if (message.details.length !== 0) {
      obj.details = base64FromBytes(message.details);
    }
    if (message.resourceVersion !== "") {
      obj.resourceVersion = message.resourceVersion;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<WatchResponse>, I>>(base?: I): WatchResponse {
    return WatchResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<WatchResponse>, I>>(object: I): WatchResponse {
    const message = createBaseWatchResponse();
    message.eventType = object.eventType ?? 0;
    message.details = object.details ?? new Uint8Array(0);
    message.resourceVersion = object.resourceVersion ?? "";
    return message;
  },
};

export type WatchServiceService = typeof WatchServiceService;
export const WatchServiceService = {
  watch: {
    path: "/api.WatchService/Watch",
    requestStream: false,
    responseStream: true,
    requestSerialize: (value: WatchRequest): Buffer => Buffer.from(WatchRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): WatchRequest => WatchRequest.decode(value),
    responseSerialize: (value: WatchResponse): Buffer => Buffer.from(WatchResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): WatchResponse => WatchResponse.decode(value),
  },
} as const;

export interface WatchServiceServer extends UntypedServiceImplementation {
  watch: handleServerStreamingCall<WatchRequest, WatchResponse>;
}

export interface WatchServiceClient extends Client {
  watch(request: WatchRequest, options?: Partial<CallOptions>): ClientReadableStream<WatchResponse>;
  watch(
    request: WatchRequest,
    metadata?: Metadata,
    options?: Partial<CallOptions>,
  ): ClientReadableStream<WatchResponse>;
}

export const WatchServiceClient = makeGenericClientConstructor(WatchServiceService, "api.WatchService") as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): WatchServiceClient;
  service: typeof WatchServiceService;
  serviceName: string;
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return globalThis.Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
