{
 "title": "Pepr Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  { "title": "Pepr Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pepr Status",
   "type": "stat",
   "description": "Pepr pod status by pod",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{container=\"server\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "up{container=\"watcher\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Scrape Duration Seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "scrape_duration_seconds{container=\"server\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "scrape_duration_seconds{container=\"watcher\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Error, Alert, Validate and Mutate Counts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }
  },
  {
   "title": "Pepr: Error Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count by(instance) (rate(pepr_errors{container=\"server\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "count by(instance) (rate(pepr_errors{container=\"watcher\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Pepr: Alert Count",
   "type": "stat",
   "description": "Count of Pepr Alerts by pod",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "pepr_alerts{container=\"server\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "pepr_alerts{container=\"watcher\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Pepr: Validate Count",
   "type": "stat",
   "description": "Count of Pepr Validate actions by pod",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "pepr_Validate_count{container=\"server\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "pepr_Validate_sum{container=\"watcher\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Pepr: Mutate Count",
   "type": "stat",
   "description": "Count of Pepr mutate actions applied by pod.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "pepr_Mutate_count{container=\"server\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "rate(pepr_Mutate_count{container=\"watcher\"}[24h])",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}