apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: memcaches.cache.pepr.dev
spec:
  group: cache.pepr.dev
  names:
    kind: Memcache
    plural: memcaches
    singular: memcache
    shortNames:
      - mc
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              description: MemcacheSpec defines the desired state of Memcache
              properties:
                size:
                  type: array
                  items:
                    type: number
                  description: Size defines the number of Memcache instances
                containerPort:
                  type: number
                  description: Port defines the port that will be used to init the container with
                    the image
                config:
                  type: object
                  properties:
                    language:
                      type: string
                    timezone:
                      type: string
                    zone:
                      type: string
                    state:
                      type: string
                    areaCode:
                      type: array
                      items:
                        type: string
                  required:
                    - language
                    - timezone
                    - zone
                    - state
                    - areaCode
                  description: Application specific configuration
              required:
                - containerPort
            status:
              type: object
              description: MemcacheStatus defines the observed state of Memcache
              properties:
                conditions:
                  type: array
                  description: Conditions describing the current state
                  items:
                    type: object
                    description: Condition contains details for one aspect of the current state of
                      this API Resource.
                    properties:
                      lastTransitionTime:
                        type: string
                        format: date-time
                        description: /** lastTransitionTime is the last time the condition transitioned
                          from one status to another. This is not guaranteed to
                          be set in happensBefore order across different
                          conditions for a given object. It may be unset in some
                          circumstances.
                      message:
                        type: string
                        description: /** message is a human readable message indicating details about
                          the transition. This may be an empty string.
                      observedGeneration:
                        type: number
                        description: /** observedGeneration represents the .metadata.generation that the
                          condition was set based upon. For instance, if
                          .metadata.generation is currently 12, but the
                          .status.conditions[x].observedGeneration is 9, the
                          condition is out of date with respect to the current
                          state of the instance.
                      reason:
                        type: string
                        description: /** reason contains a programmatic identifier indicating the reason
                          for the condition's last transition. Producers of
                          specific condition types may define expected values
                          and meanings for this field, and whether the values
                          are considered a guaranteed API. The value should be a
                          CamelCase string. This field may not be empty.
                      status:
                        type: string
                        description: /** status of the condition, one of True, False, Unknown.
                      work:
                        type: object
                        properties:
                          name:
                            type: string
                          namespace:
                            type: string
                          status:
                            type: string
                          message:
                            type: string
                        required:
                          - name
                          - namespace
                          - status
                          - message
                        description: /** Work location.
                    required:
                      - lastTransitionTime
                      - message
                      - reason
                      - status
      subresources:
        status: {}
