apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: peprstores.pepr.dev
spec:
  conversion:
    strategy: None
  group: pepr.dev
  names:
    kind: PeprStore
    listKind: PeprStoreList
    plural: peprstores
    singular: peprstore
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          data:
            additionalProperties:
              type: string
            type: object
        type: object
    served: true
    storage: true
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: pepr-system
  name: pepr-system
spec: {}
