name: Node.js CI

on:
  merge_group:
  push:
  pull_request:

permissions:
  id-token: write # This is needed for OIDC federation.
  contents: read

jobs:
  check-paths:
    runs-on: ubuntu-latest
    outputs:
      code-changed: ${{ steps.filter.outputs.code }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
        id: filter
        with:
          filters: |
            code:
              - '**'
              - '!**.md'
              - '!LICENSE'
              - '!CODEOWNERS'

  on-demand-workflows:
    needs: check-paths
    uses: ./.github/workflows/on-demand-workflows.yaml
    secrets:
      CODECOV_ORG_TOKEN: ${{ secrets.CODECOV_ORG_TOKEN }}
    with:
      run-format: ${{ needs.check-paths.outputs.code-changed == 'true' }}
      run-units: ${{ needs.check-paths.outputs.code-changed == 'true' }}
      run-integration: ${{ needs.check-paths.outputs.code-changed == 'true' }}

