name: Node.js CI

on:
  merge_group:
  push:
  pull_request:

permissions:
  id-token: write # This is needed for OIDC federation.
  contents: read

jobs:
  check-paths:
    runs-on: ubuntu-latest
    outputs:
      code-changed: ${{ steps.filter.outputs.code }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: dorny/paths-filter@ceb8a2b8f2d89434be7ff52d3de7ec3738c5cc9d # v4.0.3
        id: filter
        with:
          filters: |
            code:
              - '**'
              - '!**.md'
              - '!LICENSE'
              - '!CODEOWNERS'

  on-demand-workflows:
    needs: check-paths
    uses: ./.github/workflows/on-demand-workflows.yaml
    secrets:
      CODECOV_ORG_TOKEN: ${{ secrets.CODECOV_ORG_TOKEN }}
    with:
      run-format: ${{ needs.check-paths.outputs.code-changed == 'true' }}
      run-units: ${{ needs.check-paths.outputs.code-changed == 'true' }}
      run-integration: ${{ needs.check-paths.outputs.code-changed == 'true' }}

