name: secret-scan
on: 
  pull_request:
    branches:
      - main
    paths-ignore:
    - "LICENSE"
    - "CODEOWNERS"
    - "**.md"

permissions:  # added using https://github.com/step-security/secure-repo
  contents: read
  
jobs:
  secret-scan: # scan for any live secrets in the repository using trufflehog
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
      with:
        egress-policy: audit
    - name: Checkout code
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        fetch-depth: 0
    - name: Default Secret Scanning
      uses: trufflesecurity/trufflehog@27b0417c16317ca9a472a9a8092acce143b49c55 # main
      with:
        extra_args: --debug --only-verified
