name: secret-scan
on: 
  pull_request:
    branches:
      - main
    paths-ignore:
    - "LICENSE"
    - "CODEOWNERS"
    - "**.md"

permissions:  # added using https://github.com/step-security/secure-repo
  contents: read
  
jobs:
  secret-scan: # scan for any live secrets in the repository using trufflehog
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
      with:
        egress-policy: audit
    - name: Checkout code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        fetch-depth: 0
    - name: Default Secret Scanning
      uses: trufflesecurity/trufflehog@cc1fe982afc515d2991365ce8d4d0dd07170fcad # main
      with:
        extra_args: --debug --only-verified
