name: Continuous Integration (CI) Tests

permissions: read-all

on:
  workflow_dispatch:
  # push:
  #   branches: [next]
  # pull_request:
  #   branches: [next]

jobs:
  ci:
    uses: ./.github/workflows/semrel-01-ci.yml
  e2e:
    needs: [ci]
    uses: ./.github/workflows/semrel-02-e2e.yml