name: Dev Testing

permissions: read-all

on:
  workflow_dispatch:
  # pull_request:
  #   branches: [next]

jobs:
  ci:
    uses: ./.github/workflows/semrel-ci.yml
  e2e:
    needs: [ci]
    uses: ./.github/workflows/semrel-e2e.yml