name: Upgrade Test - Upstream

on:
  merge_group:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths-ignore:
    - "**.md"
    - "LICENSE"
    - "CODEOWNERS"

  pull_request:
    branches: ["main"]
    paths-ignore:
    - "**.md"
    - "LICENSE"
    - "CODEOWNERS"

permissions:
  contents: read

jobs:
  upgrade-upstream:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write # Required by chainguard-dev/setup-chainctl step

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Login to Chainguard
        uses: chainguard-dev/setup-chainctl@2cddd35a2f120d9973e58094dc6878c93cf58c28 # v0.5.1
        with:
          identity: ${{ secrets.CHAINGUARD_IDENTITY }}

      - name: Use Node.js 26
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 26
          cache: "npm"

      - name: install k3d
        uses: ./.github/actions/setup-k3d

      - run: npm ci
      - run: |
          export PEPR_IMAGE=pepr:dev 
          npm run test:upgrade:upstream

